apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-web
  template:
    metadata:
      labels:
        app: frontend-web
    spec:
      containers:
      - name: frontend-web
        image: makuiyu/frontend-web:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: API_BASE_URL
          value: "localhost:30000"
        - name: USER_BASE_URL
          value: "user-service:5001"
        - name: ORDER_BASE_URL
          value: "order-service:5002"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-web
spec:
  selector:
    app: frontend-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer