apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
      - name: gateway-service
        image: makuiyu/gateway-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_ENV
          value: "production"
        - name: USER_SERVICE_HOST
          value: "user-service"
        - name: USER_SERVICE_PORT
          value: "5001"
        - name: ORDER_SERVICE_HOST
          value: "order-service"
        - name: ORDER_SERVICE_PORT
          value: "5002"
        - name: INVENTORY_SERVICE_HOST
          value: "inventory-service"
        - name: INVENTORY_SERVICE_PORT
          value: "5003"
        - name: PAYMENT_SERVICE_HOST
          value: "payment-service"
        - name: PAYMENT_SERVICE_PORT
          value: "5004"
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  selector:
    app: gateway-service
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30000
  type: NodePort